const time = "2026-10-02T12:00:00.000Z";
// Synthetic examples of the real authenticated export projection, never public recording data.
export function exportsInput(approvalComment = "Synthetic automated approval for demonstration only.") {
  const decision = { id: "decision-private", decisionType: "remove-from-service", proposal: "remove-from-service", riskLevel: "critical", approvalPolicyId: "asset-removal-approval", status: "awaiting-approval", decidedAt: null };
  const record = { id: "case-private", workspaceId: "workspace-private", caseType: "reliability-case", title: "A-142", status: "open", severity: "critical", priority: "urgent", owner: "maintenance-team", dueAt: time, relatedEventIds: ["event-private"], actionItems: [{ id: "action-private", actionType: "inspection", title: "Inspect", assignee: "maintenance-team", status: "open", dueAt: time, completedAt: null }], decisions: [decision], approvals: [] as unknown[] };
  const entry = (action: string, subjectId: string, data: object) => ({ id: action, workspaceId: record.workspaceId, occurredAt: time, actor: { type: action === "observation-accepted" || action === "decision-approved" ? "human" : "system", id: "session-private" }, subject: { type: action === "observation-accepted" ? "observation" : action === "rule-evaluated" ? "operational-event" : "decision", id: subjectId }, action, data });
  return {
    pending: { dataset: "cases", syntheticDataNotice: "Synthetic demo data only", records: [structuredClone(record)] },
    final: { dataset: "cases", syntheticDataNotice: "Synthetic demo data only", records: [{ ...record, decisions: [{ ...decision, status: "approved", decidedAt: time }], approvals: [{ id: "approval-private", decisionId: decision.id, approver: "session-private", outcome: "approved", comment: approvalComment, approvedAt: time }] }] },
    audit: { dataset: "audit", syntheticDataNotice: "Synthetic demo data only", records: [entry("observation-accepted", "observation-private", { schemaKey: "previous-repair-reference", previousReviewStatus: "pending", reviewStatus: "accepted" }), entry("rule-evaluated", "event-private", { ruleId: "safety-critical-removal-approval", ruleVersion: "1.0.0", result: true, condition: { kind: "all", result: true, children: [{ kind: "comparison", result: true, operator: "equals", expected: "safety-critical", fact: { exists: true, value: "safety-critical", fact: { kind: "observation", schemaKey: "severity-indicator", field: "value" }, relatedEventIds: [] } }, { kind: "comparison", result: true, operator: "greater-than-or-equal", expected: 2, fact: { exists: true, value: 4, fact: { kind: "aggregate", aggregate: "related-event-count", withinHours: 1440 }, relatedEventIds: ["event-private", "event-two", "event-three", "event-four"] } }] } }), entry("decision-proposed", decision.id, { caseId: record.id, ruleId: "safety-critical-removal-approval", ruleVersion: "1.0.0", riskLevel: "critical", approvalPolicyId: decision.approvalPolicyId }), entry("decision-approved", decision.id, { caseId: record.id, approvalId: "approval-private", previousDecisionStatus: "awaiting-approval", outcome: "approved" })] },
    stages: { fieldKey: "previous-repair-reference", confidence: "70%", excerpt: "it had brake work done back in the spring", pendingStatus: "Pending review", queueCleared: true, ruleId: "safety-critical-removal-approval", ruleVersion: "1.0.0", ruleEventId: "event-private", severityValue: "safety-critical", aggregateValue: 4, commentRequired: true, approvalComment },
  };
}
